SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

DROP DATABASE IF EXISTS `cu99893_art`;
CREATE DATABASE IF NOT EXISTS `cu99893_art` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE `cu99893_art`;

DROP TABLE IF EXISTS `Dist`;
CREATE TABLE IF NOT EXISTS `Dist` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `img_a` int(11) NOT NULL,
  `img_b` int(11) NOT NULL,
  `dist` double DEFAULT NULL,
  `version` int(11) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS `Img`;
CREATE TABLE IF NOT EXISTS `Img` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `id_user` int(11) DEFAULT NULL,
  `path` text,
  `predx` double DEFAULT NULL,
  `predy` double DEFAULT NULL,
  `predz` double DEFAULT NULL,
  `version` int(11) NOT NULL DEFAULT '1',
  `src` text,
  `url` varchar(255) DEFAULT NULL,
  `hash` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `url` (`url`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
DROP TRIGGER IF EXISTS `CalcDist`;
DELIMITER $$
CREATE TRIGGER `CalcDist` AFTER INSERT ON `Img` FOR EACH ROW INSERT INTO Dist (img_a, img_b, dist) 
  SELECT NEW.id, id, 
  POW(
      POW(predx-NEW.predx, 2) +
      POW(predy-NEW.predy, 2) +
      POW(predz-NEW.predz, 2)
      , 0.5)
  FROM Img
  WHERE id<>NEW.id
$$
DELIMITER ;
DROP TRIGGER IF EXISTS `DeleteImg`;
DELIMITER $$
CREATE TRIGGER `DeleteImg` BEFORE DELETE ON `Img` FOR EACH ROW DELETE FROM Dist 
	WHERE img_a=old.id OR
    	  img_b=old.id
$$
DELIMITER ;
DROP TRIGGER IF EXISTS `RndUrl`;
DELIMITER $$
CREATE TRIGGER `RndUrl` BEFORE INSERT ON `Img` FOR EACH ROW SET NEW.url = MD5(RAND())
$$
DELIMITER ;

DROP TABLE IF EXISTS `User`;
CREATE TABLE IF NOT EXISTS `User` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `soc` bigint(20) NOT NULL,
  `name` json NOT NULL,
  `ava` int(11) DEFAULT NULL,
  `id_soc` int(11) DEFAULT '1',
  `date_regist` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
DROP TRIGGER IF EXISTS `DeleteUser`;
DELIMITER $$
CREATE TRIGGER `DeleteUser` BEFORE DELETE ON `User` FOR EACH ROW DELETE FROM Img 
	WHERE id_user=old.id
$$
DELIMITER ;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
